### ISSUE TITLE
clientlib is unable to update the files/resources from dist to ui.apps. Throwing new errors everytime. Note that it is working fine on Mac but on windows only throwing errors.

### ISSUE THREAD

**Issue by pankajpj07** [wcm-io-frontend/aem-clientlib-generator#47]
watch "clientlib" ./dist && aemsync -w ../ui.apps/src/main/content
> Watching ./dist
(node:16216) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, chmod 'C:\Users\C286533\Pankaj\digital_emcm-web\uefalcon\ui.apps\src\main\content\jcr_root\apps\uefalcon\clientlibs\clientlib-dependencies\resources\0.js'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:16216) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:16216) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
internal/fs/utils.js:307
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'C:\Users\C286533\Pankaj\digital_emcm-web\uefalcon\ui.apps\src\main\content\jcr_root\apps\uefalcon\clientlibs\clientlib-dependencies\js.txt'
    at Object.openSync (fs.js:476:3)
    at Object.writeFileSync (fs.js:1467:35)
    at writeAssetTxt (C:\Users\C286533\Pankaj\digital_emcm-web\uefalcon\ui.frontend\node_modules\aem-clientlib-generator\lib\clientlib.js:163:8)
    at C:\Users\C286533\Pankaj\digital_emcm-web\uefalcon\ui.frontend\node_modules\aem-clientlib-generator\lib\clientlib.js:515:9
    at C:\Users\C286533\Pankaj\digital_emcm-web\uefalcon\ui.frontend\node_modules\aem-clientlib-generator\node_modules\async\dist\async.js:2588:44
    at replenish (C:\Users\C286533\Pankaj\digital_emcm-web\uefalcon\ui.frontend\node_modules\aem-clientlib-generator\node_modules\async\dist\async.js:446:21)
    at C:\Users\C286533\Pankaj\digital_emcm-web\uefalcon\ui.frontend\node_modules\aem-clientlib-generator\node_modules\async\dist\async.js:451:13
    at eachLimit$1 (C:\Users\C286533\Pankaj\digital_emcm-web\uefalcon\ui.frontend\node_modules\aem-clientlib-generator\node_modules\async\dist\async.js:2718:34)
    at awaitable (C:\Users\C286533\Pankaj\digital_emcm-web\uefalcon\ui.frontend\node_modules\aem-clientlib-generator\node_modules\async\dist\async.js:211:32)
    at Object.eachSeries (C:\Users\C286533\Pankaj\digital_emcm-web\uefalcon\ui.frontend\node_modules\aem-clientlib-generator\node_modules\async\dist\async.js:2746:16) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\C286533\\Pankaj\\digital_emcm-web\\uefalcon\\ui.apps\\src\\main\\content\\jcr_root\\apps\\uefalcon\\clientlibs\\clientlib-dependencies\\js.txt'
}

**Comment by JoSchae** [comment]
This still persists.

Also throws this kind of error

`[clientlib] Error: EPERM: operation not permitted, open 'C:\Users\JohannesSchäfer\GIT\projectname\ui.apps\src\main\content\jcr_root\apps\projectname\clientlibs\themes\clientlib-stopgo\.content.xml'
[clientlib]     at Object.openSync (node:fs:585:3)
[clientlib]     at Object.writeFileSync (node:fs:2155:35)
[clientlib]     at writeClientLibXml (C:\Users\JohannesSchäfer\GIT\projectname\ui.frontend\node_modules\aem-clientlib-generator\lib\clientlib.js:239:9)        
[clientlib]     at C:\Users\JohannesSchäfer\GIT\projectname\ui.frontend\node_modules\aem-clientlib-generator\lib\clientlib.js:504:9
[clientlib]     at wrapper (C:\Users\JohannesSchäfer\GIT\projectname\ui.frontend\node_modules\async\dist\async.js:271:20)
[clientlib]     at iterateeCallback (C:\Users\JohannesSchäfer\GIT\projectname\ui.frontend\node_modules\async\dist\async.js:419:21)
[clientlib]     at C:\Users\JohannesSchäfer\GIT\projectname\ui.frontend\node_modules\async\dist\async.js:327:20
[clientlib]     at CB (C:\Users\JohannesSchäfer\GIT\projectname\ui.frontend\node_modules\fs-extra\lib\remove\rimraf.js:57:5)
[clientlib]     at C:\Users\JohannesSchäfer\GIT\projectname\ui.frontend\node_modules\fs-extra\lib\remove\rimraf.js:204:24
[clientlib]     at CB (C:\Users\JohannesSchäfer\GIT\projectname\ui.frontend\node_modules\fs-extra\lib\remove\rimraf.js:57:5) {
[clientlib]   errno: -4048,
[clientlib]   syscall: 'open',
[clientlib]   code: 'EPERM',
[clientlib]   path: 'C:\\Users\\JohannesSchäfer\\GIT\\projectname\\ui.apps\\src\\main\\content\\jcr_root\\apps\\projectname\\clientlibs\\themes\\clientlib-stopgo\\.content.xml'
[clientlib] }
[clientlib] node:internal/fs/utils:344
[clientlib]     throw err;
[clientlib]     ^
[clientlib]`

**Comment by stefanseifert** [comment]
there seems to be a problem in your environment. we are using the same aem-clientlib-generator configuration successfully on macos, windows and linux environments. for the recent version, we have also added integration tests with all three environment here running via github actions.
